### ISSUE TITLE
Could not resolve view with name 'xxxx' in servlet with name 'yyyy'

### ISSUE THREAD

**Issue by eharris369** [spring-projects/eclipse-integration-tcserver#4]
I have an application that fails when using STS (see stack trace below) but works if I install Oxygen and then STS on top of it.   Are there any differences between the two (project structure, how the projects get built, etc.) that might cause this?  Are there any differences between the Tomcat that comes with STS and regular Tomcat?

javax.servlet.ServletException: Could not resolve view with name 'xxxx' in servlet with name 'yyyy'
at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1266)
at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1041)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:984)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

**Comment by martinlippert** [comment]
In general, STS is Eclipse with the Spring Tools extensions pre-installed (plus a few extra third-party plugins that we find useful). So that doesn't explain the issue you are reporting.

The tc-Server that comes with STS is different than pure Tomcat, but it shouldn't make a huge difference when running apps from STS. Can you point us to an example project somewhere that reproduces the issue and describe a few steps how to reproduce this? Would love to take a deeper look at this.

**Comment by eharris369** [comment]
Thanks for your reponse.  This is actually a customer and they don't want to share their application.  Do you have any ideas as to what can cause that type of error message?  Does it indicate that something is missing?

**Comment by martinlippert** [comment]
You said this app works when you deploy this to a regular Tomcat from within Eclipse (with additional STS components installed). If that is the case, it would be interesting to know if this works too in STS (not deploying to the tc-Server that comes with STS, but to a regular Tomcat, configured in STS as you did in Eclipse). Can you double check that?

**Comment by martinlippert** [comment]
In case of the tc-server deploy, you can always check what exactly got deployed by looking into the webapps folder of the instance that you use wit that tc-server install (if that helps).
