### ISSUE TITLE
[tc server 4.x] No way to configure tc server 4.x standard edition

### ISSUE THREAD

**Issue by lak-proddev** [spring-projects/eclipse-integration-tcserver#5]
Unable to  add tc server 4.0.1 standard edition. **Not developer edition.**

1.Downloaded  tc server 4.0.1 standard edition from here. https://network.pivotal.io/products/pivotal-tcserver
2.Installed  "Pivotal tc Server Integration for Eclipse" 3.9.4.201804120859-RELEASE" on Photon Release Candidate 2 (4.8.0RC2).
3.While trying to  configure new server adapter, I can see attached  exception and not able to finish the wizard.
[tc_server_exception.txt](https://github.com/spring-projects/eclipse-integration-tcserver/files/2126292/tc_server_exception.txt)
![tc_standard2](https://user-images.githubusercontent.com/39690425/41757626-d2d6a97e-7600-11e8-8818-d9eb2e6edb18.png)

4.I think, this part of the code is  causing the issue.

TcServerRuntime40.java at lines 38-40 
 public boolean accept(File dir, String name) {
 **return Pattern.matches("developer-\\d\\.\\d\\.\\d\\.(RELEASE|SNAPSHOT-BUILD)", name) && new** File(dir, name).isDirectory();
}

**Comment by BoykoAlex** [comment]
Should be fixed now. Please try http://dist.springsource.com/snapshot/TOOLS/eclipse-integration-tcserver/nightly

**Comment by lak-proddev** [comment]
Still, I can see the attached NPE .
https://github.com/spring-projects/eclipse-integration-tcserver/files/2126292/tc_server_exception.txt


I think, this method shouldn't return `null`

_**com.vmware.vfabric.ide.eclipse.tcserver.internal.core.TcServerRuntime40.getTcServerRuntimePath(IPath)**_

**Comment by BoykoAlex** [comment]
I don't see the NPE. Hope you trying 3.9.5 or 3.9.4 with tc server integration from the nightly p2 repo posted above.
How do you get the NPE? What's the folder structure for tc server runtime? For me it is:
pivotal-tc-server
-- standard-4.0.2.RELEASE
-- instances
-- runtimes

**Comment by lak-proddev** [comment]
I can see this exception on 
`Spring Tool Suite` 
`Version: 3.9.5.RELEASE`
`Build Id: 201807031753`
`Platform: Eclipse Photon (4.8.0)`

![image](https://user-images.githubusercontent.com/39690425/43059057-596cd7ae-8e68-11e8-8cee-484cf5ff9c1f.png)

If you give any invalid directory and press `Finish`, You will get this  exception.

![image](https://user-images.githubusercontent.com/39690425/43059110-923c26b6-8e68-11e8-91bf-27c7ef3f39b8.png)

java.lang.NullPointerException
	at org.eclipse.jst.server.tomcat.ui.internal.TomcatRuntimeWizardFragment.exit(TomcatRuntimeWizardFragment.java:63)
	at com.vmware.vfabric.ide.eclipse.tcserver.internal.ui.TcServerRuntimeWizardFragment.exit(TcServerRuntimeWizardFragment.java:116)
	at org.eclipse.wst.server.ui.internal.wizard.TaskWizard.performFinish(TaskWizard.java:159)
	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:772)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:411)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:81)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4118)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1052)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3931)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3534)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.eclipse.wst.server.ui.internal.RuntimePreferencePage.showWizard(RuntimePreferencePage.java:396)
	at org.eclipse.wst.server.ui.internal.RuntimePreferencePage$2.widgetSelected(RuntimePreferencePage.java:146)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4118)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1052)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3931)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3534)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.eclipse.ui.internal.dialogs.WorkbenchPreferenceDialog.open(WorkbenchPreferenceDialog.java:211)
	at org.eclipse.wst.server.ui.internal.wizard.page.NewManualServerComposite.showPreferencePage(NewManualServerComposite.java:375)
	at org.eclipse.wst.server.ui.internal.wizard.page.NewManualServerComposite$9.widgetSelected(NewManualServerComposite.java:344)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4118)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1052)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1076)
	at org.eclipse.swt.widgets.Widget.sendSelectionEvent(Widget.java:1093)
	at org.eclipse.swt.widgets.Link.WM_LBUTTONUP(Link.java:1009)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4802)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4757)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2303)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3532)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.eclipse.wst.server.ui.internal.actions.LaunchWizardAction.run(LaunchWizardAction.java:58)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4118)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1052)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3931)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3534)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1170)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1059)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:667)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:597)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1498)

**Comment by BoykoAlex** [comment]
Thanks! Hopefully fixed with bcefb0517f2bcf0283dbd1479d1cba1e729df457
